---
- name: reboot | Rebooting Server
  win_reboot:
    reboot_timeout_sec: "{{ reboot_timeout }}"
    shutdown_timeout_sec: "{{ shutdown_timeout }}"
  when: ansible_user_id != "vagrant"

- name: reboot | Vagrant style reboot
  win_shell: Restart-Computer -Force
  when: ansible_user_id == "vagrant"
  register: vagrant_reboot

- name: reboot | Wait 2 min for Vagrant reboot.yml
  pause:
    seconds: 120
  when: >
    vagrant_reboot is defined and
    vagrant_reboot